"""
ai_context_exporter.py

Creates AI context metadata.

This file tells an AI model:

- what the export contains
- how to interpret files
- how to reason about the binary
"""


import os
import datetime


from util.jsonwriter import JSONWriter



class AIContextExporter(object):


    VERSION = "1.0.0"



    def __init__(
            self,
            program,
            monitor,
            output,
            config):


        self.program = program
        self.monitor = monitor
        self.output = output
        self.config = config



    # --------------------------------------------------------
    # Export
    # --------------------------------------------------------

    def export(self):


        context = {


            "exporter":

            {

                "name":
                    "Ghidra AI Exporter",

                "version":
                    self.VERSION

            },


            "created":

                str(
                    datetime.datetime.now()
                ),



            "binary":

            {

                "name":
                    self.program.getName(),

                "architecture":
                    str(
                        self.program
                        .getLanguage()
                    )

            },



            "purpose":

            "This dataset is a static reverse engineering knowledge base generated from Ghidra.",



            "files":

            {


                "manifest":

                    "manifest.json",


                "functions":

                    "functions/*.json",


                "strings":

                    "strings.json",


                "imports":

                    "imports.json",


                "callgraph":

                    "callgraph.json"


            },



            "analysis_rules":

            [

                "Function names may be autogenerated.",

                "Decompiler output is reconstructed code.",

                "Assembly should be consulted when C output is unclear.",

                "Use call relationships to understand execution flow.",

                "Cross reference addresses between files.",

                "Do not assume FUN_ names describe behaviour."

            ],



            "recommended_workflow":

            [

                "Read manifest.json first.",

                "Identify important imports.",

                "Search strings for interesting indicators.",

                "Follow callgraph relationships.",

                "Inspect function JSON files."

            ]

        }



        path = os.path.join(

            self.output,

            "ai_context.json"

        )



        JSONWriter.save(

            path,

            context

        )


        print(
            "[+] AI context written"
        )
