"""
ai_context_exporter.py

Creates AI context metadata.

This file tells an AI model:

- what the export contains
- how to interpret files
- how to reason about the binary
"""


import os
import datetime
import json


from util.jsonwriter import JSONWriter



class AIContextExporter(object):


    VERSION = "1.0.0"



    def __init__(
            self,
            program,
            monitor,
            output,
            config):


        self.program = program
        self.monitor = monitor
        self.output = output
        self.config = config



    # --------------------------------------------------------
    # Export
    # --------------------------------------------------------

    def export(self):

        binary_name, architecture = self._binary_metadata()


        context = {


            "exporter":

            {

                "name":
                    "Ghidra AI Exporter",

                "version":
                    self.VERSION

            },


            "created":

                str(
                    datetime.datetime.now()
                ),



            "binary":

            {

                "name":
                    binary_name,

                "architecture":
                    architecture

            },



            "purpose":

            "This dataset is a static reverse engineering knowledge base generated from Ghidra.",



            "files":

            {


                "manifest":

                    "manifest.json",


                "functions":

                    "functions/*.json",


                "strings":

                    "strings.json",


                "imports":

                    "imports.json",


                "callgraph":

                    "callgraph.json"


            },



            "analysis_rules":

            [

                "Function names may be autogenerated.",

                "Decompiler output is reconstructed code.",

                "Assembly should be consulted when C output is unclear.",

                "Use call relationships to understand execution flow.",

                "Cross reference addresses between files.",

                "Do not assume FUN_ names describe behaviour."

            ],



            "recommended_workflow":

            [

                "Read manifest.json first.",

                "Identify important imports.",

                "Search strings for interesting indicators.",

                "Follow callgraph relationships.",

                "Inspect function JSON files."

            ]

        }



        path = os.path.join(

            self.output,

            "ai_context.json"

        )



        JSONWriter.save(

            path,

            context

        )


        print(
            "[+] AI context written"
        )


    def _binary_metadata(self):
        """Read binary metadata from Ghidra or a completed export manifest."""

        if self.program is not None:
            return (
                self.program.getName(),
                str(self.program.getLanguage())
            )

        manifest_path = os.path.join(self.output, "manifest.json")
        with open(manifest_path, "r", encoding="utf-8") as handle:
            manifest = json.load(handle)

        binary = manifest.get("binary", {})
        language = manifest.get("language", {})
        binary_name = binary.get("name")
        architecture = language.get("id") or language.get("processor")

        if not binary_name or not architecture:
            raise ValueError(
                "manifest.json must contain binary.name and language.id or language.processor"
            )

        return binary_name, str(architecture)
